require 'capistrano/chruby'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'capistrano/provision/provision'
require 'capistrano/provision/rails'
require 'capistrano/provision/deploy'
require 'capistrano/provision/load'
